services:
  webapp:
    container_name: pyspark_notebook
    build: 
      args:
        GOOGLE_APPLICATION_CREDENTIALS: ${GOOGLE_APPLICATION_CREDENTIALS}
        JSON_KEYFILE_NAME: ${JSON_KEYFILE_NAME}
    command: start.sh jupyter lab --LabApp.token=''
    ports:
      - "8888:8888"
    volumes:
      - ${NOTEBOOKS_PATH}:/home/jovyan/work/notebooks/
      - ${SRC_PATH}:/home/jovyan/work/src/
      - ${DATA_PATH}:/home/jovyan/work/data/
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      PYARROW_IGNORE_TIMEZONE: 1